Added script for control flow and relation Operator Section
learnPythonGit/pythonGitRepo pull request #12
Opened 2020-04-14 16:47 UTC by saurav1628

Hi All,
Added script for control flow and relation Operator Section

Please review and merge

Thanks,
Saurav

2020-04-14 17:11 UTC, kiranrlohar approved these changes

2020-04-14 18:03 UTC, ashish-kulthe requested changes
Please make necessary changes.

2020-04-15 15:33 UTC, saurav1628 commented
@ashish-kulthe ,
I have made required changes, Please review and merge

2020-04-15 16:53 UTC, ashish-kulthe approved these changes

2020-04-15 16:53 UTC, merged