Commiting assignment on List date 12/04/2020
learnPythonGit/pythonGitRepo pull request #4
Opened 2020-04-12 14:55 UTC by kiranrlohar

I have gone through videos of String List Dictionary today and tried to write simple assignment on List using for loop. Kindly review and comment.

2020-04-12 15:09 UTC, saurav1628 requested changes
For first program else statement should be included which will indicate if Manufacturer is not present in the list than what to do with the vehicle.

2020-04-12 15:25 UTC, kiranrlohar commented
Got it. Will add the else condition for each manufacturer condition and print the appropriate message.

2020-04-12 15:53 UTC, saurav1628 submitted a review, later dismissed

2020-04-13 14:54 UTC, saurav1628 approved these changes

2020-04-13 15:12 UTC, ashish-kulthe approved these changes
looks good

2020-04-13 15:17 UTC, merged